server:
  port: 12000  #端口号
spring:
  application:
    name: tensquare-config   #配置微服务名称
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/qsmshang/tensquare-config.git
  rabbitmq:
    host: 127.0.0.1
management:  #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
