server:
  port: 9009
spring:
  application:
    name: tensquare-spit #指定服务名称
  data:
    mongodb:
      host: 127.0.0.1
      database: spitdb
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
