server:
  port: 9008
spring:
  application:
    name: tensquare_user #指定服务名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_user?characterEncoding=utf-8
    username: root
    password: root1234
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 127.0.0.1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
jwt:
  config:
    key: shang  #jwtToken签名key
    ttl: 3600000 #jwtToken过期时间